config/routes.rb
Rails.application.routes.draw do
  
  #Prototyping route
  get 'static_pages/:view', to: 'static_pages#show'

  get '/styleguide' => 'styleguide#index'
  get '/styleguide/:action' => 'styleguide'
  # PWA Routes
  get '/site' => 'service_worker#webmanifest', format: :webmanifest, as: :webmanifest
  get '/service-worker' => 'service_worker#index', format: :js, as: :service_worker
  resources :uploads do
    post :image, on: :collection
  end
  get 'hello_world', to: 'hello_world#index'
  resources :documents, only: [:show]
  resources :images, only: [:show]
  resources :assets, only: [:show]
  resources :pages, only: [:show], as: :koi_pages
  root to: 'pages#index'
  mount Koi::Engine => "/admin", as: "koi_engine"
  get "/:id"  => "pages#show", as: :page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_analytics.html.erb
<%- ga_key = get_koi_site_setting("site.google_analytics.profile_id") -%>
<%- if ga_key -%>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '<%= ga_key -%>', 'auto');
    <%= yield :custom_ga -%>
    if(!Ornament.features.turbolinks) {
      ga('send', 'pageview');
    }
  </script>
<%- end -%>

app/views/layouts/_seo.html.erb
<%-

  cache_version ||= "1"
  koi_settings ||= true

  # Defaults 
  seo_title ||= "Ornament Pattern Library and UI/UX Documentation"
  seo_title_postfix ||= seo_title
  seo_keywords ||= false
  seo_description ||= ""
  seo_image ||= false # "#{root_url}assets/share.png?v=#{cache_version}"
  theme_colour ||= "#4b9dd0";
  use_pwa_settings ||= false

  # Twitter Settings
  twitter_handle ||= ""
  twitter_creator ||= ""

  # Koi Site Settings 
  if defined?(Translation) && koi_settings 
    koi_title = Translation.find_by_key('site.title').try(:value)
    koi_description = Translation.find_by_key('site.meta_description').try(:value)
    koi_keywords = Translation.find_by_key('site.meta_keywords').try(:value)
    site_settings_title = clean_share_input(koi_title) if koi_title
    site_settings_meta = clean_share_input(koi_description) if koi_description
    site_settings_keywords = clean_share_input(koi_keywords) if koi_keywords
    seo_title = site_settings_title if !koi_title.blank?
    seo_title_postfix = seo_title if !koi_title.blank?
  end

  # Page Title
  if !seo("title").blank?
    seo_title = seo("title")
  elsif content_for?(:page_title)
    seo_title = yield(:page_title)
  elsif content_for?(:title)
    seo_title = yield(:title)
  elsif content_for?(:og_title)
    seo_title = yield(:og_title)
  end

  # Append | <postfix> to the end of title if necessary
  if !seo_title_postfix.blank? && !seo_title.include?(seo_title_postfix)
    seo_title = raw "#{seo_title} - #{seo_title_postfix}"
  end

  # Meta Description
  if !seo("meta_description").blank?
    seo_description = clean_share_input(seo('meta_description'))
  elsif content_for?(:og_description) 
    seo_description = yield(:og_description)
  elsif site_settings_meta.present?
    seo_description = clean_share_input(site_settings_meta)
  end

  # Meta Keywords
  if !seo("meta_keywords").blank?
    seo_keywords = clean_share_input(seo('meta_keywords'))
  elsif site_settings_keywords.present?
    seo_keywords = clean_share_input(site_settings_keywords)
  end

  # Meta Image
  if content_for?(:meta_image)
    seo_image = yield(:meta_image)
  end

  # Facebook Title
  if content_for?(:og_title) 
    facebook_title = yield(:og_title)
  else
    facebook_title = seo_title
  end

  # Facebook description
  if content_for?(:og_description)
    facebook_description = yield(:og_description)
  else
    facebook_description = seo_description
  end

  # Facebook author
  facebook_author = content_for?(:og_author) ? yield(:og_author) : false

  # Facebook publish time
  facebook_publish_time = content_for?(:og_publish_time) ? yield(:og_publish_time) : false

  # Facebook image
  if content_for?(:og_image)
    facebook_image = yield(:og_image)
  elsif content_for?(:meta_image)
    facebook_image = yield(:meta_image)
  else
    facebook_image = seo_image
  end

  # Twitter Image
  if content_for?(:twitter_image)
    twitter_image = yield(:twitter_image)
  elsif content_for(:og_image)
    twitter_image = yield(:og_image)
  elsif content_for(:meta_image)
    twitter_image = yield(:meta_image)
  else
    twitter_image = seo_image
  end

  # Add base URL to facebook image
  facebook_image = absolute_url(facebook_image)

  # Add base URL to twitter image
  twitter_image = absolute_url(twitter_image)

  # Thene Colour
  if content_for?(:meta_theme_colour)
    theme_colour = yield(:meta_theme_colour)
  end

-%>

<%# Meta %>
<title><%= seo_title -%></title>
<meta name="description" content="<%= raw seo_description %>">
<%- if seo_keywords -%>
  <meta name="keywords" content="<%= raw seo_keywords %>">
<%- end -%>
<%- if facebook_image -%>
  <link rel="image_src" href="<%= facebook_image -%>" />
<%- end -%>

<%# Facebook %>
<%- if facebook_image && !content_for?(:disable_og_image) -%>
  <meta property="og:image" content="<%= facebook_image -%>" />
<%- end -%>
<meta property="og:title" content="<%= facebook_title -%>" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:description" content="<%= raw facebook_description -%>">
<%- if facebook_author -%>
  <meta property="og:author" content="<%= facebook_author -%>" />
<%- end -%>
<%- if facebook_publish_time -%>
  <meta property="og:published_time" content="<%= facebook_publish_time -%>" />
<%- end -%>

<%# Twitter %>
<meta name="twitter:card" content="summary" />
<%- unless twitter_handle.blank? -%>
  <meta name="twitter:site" content="<%= twitter_handle -%>" />
<%- end -%>
<%- unless twitter_image.blank? -%>
  <meta name="twitter:image" content="<%= twitter_image -%>" />
<%- end -%>
<%- unless twitter_creator.blank? -%>
  <meta name="twitter:creator" content="<%= twitter_creator -%>">
<%- end -%>
<meta name="twitter:title" content="<%= seo_title -%>">
<meta name="twitter:url" content="<%= request.original_url %>">
<meta name="twitter:description" content="<%= raw seo_description -%>">

<%# Application Icons %>
<% if use_pwa_settings %>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="<%= webmanifest_path(format: :webmanifest) %>">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="<%= theme_colour %>">
  <meta name="theme-color" content="<%= theme_colour %>">
<% end %>

<%# Strucuted Data for enhanced search results %>
<%# Docs - https://developers.google.com/search/docs/guides/enhance-site %>
<%# Testing tool - https://search.google.com/structured-data/testing-tool %>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  <% if content_for?(:structured_data) %>
    <%= yield :structured_data %>
  <% else %>
    "@type": "Organization",
    "url": "<%= root_url %>",
    "logo": "<%#= asset_url("logo.png") %>"
  <% end %>
}
</script>

app/views/layouts/_webfonts.html.erb
<%- config ||= {
  # google: {
  #   families: ['Open Sans:400,700,400italic,700italic'],
  # }
} -%>

<%- if config -%>
  <script>
    WebFontConfig = <%= raw config.to_json -%>;
    (function(d) {
      var wf = d.createElement('script'), s = d.scripts[0];
      wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js';
      s.parentNode.insertBefore(wf, s);
    })(document);
  </script>
<%- end -%>

app/views/layouts/application.html.erb
<% content_for :global do %>

  <%- content_for :page_main do -%>
    <% if content_for? :title %>
      <h1 class="heading-one page--title">
        <%= yield :title %>
      </h1>
    <% end %>
    <%= content_for?(:application) ? yield(:application) : yield %>
  <%- end -%>

  <%- if content_for? :sidebar -%>
    <div class="page__with-sidebar">
      <div class="page--main">
        <%= yield :page_main -%>
      </div>
      <div class="page--sidebar">
        <%= yield :sidebar -%>
      </div>
    </div>
  <%- elsif content_for? :sidebar_right -%>
    <div class="page__with-sidebar-right">
      <div class="page--main">
        <%= yield :page_main -%>
      </div>
      <div class="page--sidebar">
        <%= yield :sidebar_right -%>
      </div>
    </div>
  <%- else -%>
    <%= yield :page_main -%>
  <%- end -%>  
  
<% end %>

<%= render :file => "layouts/global" %>

app/views/layouts/global.html.erb
<!DOCTYPE html>
<html lang="en">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">

    <%# Meta tags %>
    <meta charset="utf-8"/>
    <%= render "layouts/seo" -%>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <% unless Rails.env == "production" %>
      <meta name="robots" content="noindex,nofollow"/>
    <% end  %>
    <%= yield :meta %>

    <script>
      Ornament = window.Ornament || {};
      // dataLayer = window.dataLayer = {};
    </script>

    <%# Styles %>
    <%= stylesheet_pack_tag "application" %>
    <%= yield :styles %>

    <%# Scripts %>
    <script>
      var Ornicons = {
        chevronLeft: "<%= escape_javascript icon("chevron_left") %>",
        chevronRight: "<%= escape_javascript icon("chevron_right") %>",
        close: "<%= escape_javascript icon("close") %>",
        starFull: "<%= escape_javascript icon("star") %>",
        starEmpty: "<%= escape_javascript icon("star", fill: "#D8D8D8") %>",
        starWhite: "<%= escape_javascript icon("star", fill: "#FFF") %>"
      }
    </script>
    <%= javascript_pack_tag "application" %>
    <%= yield :scripts %>

    <%# Google Tag Manager - GTM-XXXXXXX %>
    <%- gtm_code = get_koi_site_setting("site.gtm_code") -%>
    <%- if gtm_code -%>
      <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','<%= gtm_code -%>');</script>
    <%- end -%>

    <%# Webfonts %>
    <%#= render "layouts/webfonts", config: {
      google: {
        families: ['Open Sans:400,700,400italic,700italic'],
      }
    } -%>

    <%# Koi Scripts %>
    <%- koi_scripts = get_koi_site_setting("site.head_scripts") -%>
    <%= koi_scripts if koi_scripts -%>

  </head>

  <body class="<%= yield :body_class -%>"> 
    <%- if gtm_code -%>
      <%# Google Tag Manager (noscript Version) %>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= gtm_code -%>" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <%- end -%>

    <a class="skip-link" href="#main">skip to content</a>

    <div class="layout tray-container" data-tray-layout>

      <div data-tray-overlay>
        <nav aria-label="Global Navigation" role="navigation">
          <ul></ul>
        </nav>
      </div>

      <div class="tray--page layout--content environment-<%= Rails.env -%>" data-tray-page>

        <header class="header" role="banner">
          <div class="layout--container">
            <%= react_component("FavouriteButton", props: {favCount: 3}) %>
            <button title="Open menu" data-tray-button>Toggle menu</button>
          </div>
        </header>

        <div data-layout-positioner class="layout--positioner tray--open-overlay">
          <%= render "/shared/oldie" -%>
          <%= yield :above_layout -%>
          <%= render "/shared/flash" -%>
          <%- if content_for?(:global) || !yield.blank? -%>
            <a id="main" name="main" tabindex="-1"></a>
            <main class="layout--main <%= yield(:layout_class) -%>" role="main">
              <div class="layout--container">
                <%= content_for?(:global) ? yield(:global) : yield %>
              </div>
            </main>
          <%- end -%>
          <%= yield :below_layout -%>
          <footer class="footer" role="contentinfo">
            <div class="layout--container">
              footer
            </div>
          </footer>
        </div>
      </div>

    </div>

    <%= yield :scripts_bottom %>

    <script>
      let customerSignedIn = false;
      let customerFavourites = [2,3,5];
    </script>
    
    <%= render "layouts/analytics" -%>

  </body>

</html>

app/views/layouts/modal.html.erb
<%= render layout: "/shared/inline_lightbox", locals: {
  title: @lightbox_title,
  lightbox_class: @lightbox_class,
  no_hide: true,
  inline_id: "modal_layout"
} do %>
  <%= yield %>
<% end %>